version: 2
jobs:
  build:
    docker:
      - image: sunslayer/latex-docker:buster

    steps:
      # ensure that Git is installed
      - run:
          name: install Git
          command: |
            apt update && apt install --no-install-recommends --yes \
                    git \
                    openssh-client

      - checkout

      - run:
          name: install dependencies
          command: |
            apt update && apt install --no-install-recommends --yes \
                    $(cat .ci/build/make/dependencies/apt.list)
            pip install --requirement .ci/build/make/dependencies/python.list

      - run:
          name: build packages
          command: make

  spelling:
    docker:
      - image: circleci/golang

    resource_class: small

    steps:
      - checkout

      - run:
          name: install
          working_directory: /usr/local/
          command: |
            curl -L https://git.io/misspell | sudo bash

      - run:
          name: misspell
          command: |
            .ci/lint/misspell/check.sh

workflows:
  version: 2
  commit:
    jobs:
      - build
      - spelling
