version: 2
jobs:
  build:
    docker:
      - image: sunslayer/latex-docker

    steps:
      - checkout

      - run:
          name: build packages
          command: |
            for package in $(find . -name Makefile); do
              make --directory="$(dirname "$package")";
            done
