version: 2
jobs:
  build:
    docker:
      - image: sunslayer/latex-docker:buster

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            apt update && apt install --no-install-recommends --yes \
                    $(cat .circleci/dependencies/apt.list)
            pip install --requirement .circleci/dependencies/python.list

      - run:
          name: build packages
          command: |
            for package in $(find . -name Makefile); do
              make --directory="$(dirname "$package")";
            done
