name: build

on:
  pull_request:
  push:

jobs:
  make:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
    steps:
      - name: Install Git
        run: |
          sudo apt update && sudo apt install --no-install-recommends --yes \
              ca-certificates \
              git
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install --no-install-recommends --yes \
              $(cat .ci/build/make/dependencies/apt.list)
          pip install --requirement .ci/build/make/dependencies/python.list
      - name: make
        run: make
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            **/*.zip
