name: lint

on:
  pull_request:
  push:

jobs:
  git-diff--check:
    name: git diff --check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: git diff --check
        uses: joel-coffman/action-git-diff-check@0.1.1

  misspell:
    name: spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
      - name: install dependencies
        run: curl -L https://git.io/misspell | sudo bash
        working-directory: /usr/local/
      - name: run misspell
        run: |
          .ci/lint/misspell/check.sh
